version: '3'

dotenv: ['.env']

env:
  WORD: world

tasks:
  helloworld:
    cmds:
      - echo "Hello, $THERE!"

  byeworld:
    cmds:
      - echo "$GREETING, $WORD!"
    env:
      GREETING: bye

  all:
    deps: [helloworld, byeworld]