version: '3'

tasks:
  hello:
    desc: "A Hello World Task"
    cmds:
      - echo "Hello World from Task!"
    silent: true

  install:
    desc: "An example of dynamic variables"
    cmds:
      - echo "Installing tool into {{.HOMEDIR}}"
    silent: true
    vars:
      HOMEDIR:
        sh: echo $HOME/.mydir

  terraform-plan:
    desc: "A mock terraform plan"
    dir: terraform
    cmds:
      - echo "Running terraform plan..."
    silent: true

  terraform-apply:
    desc: "A mock terraform apply"
    dir: terraform
    deps: [terraform-plan]
    cmds:
      - echo "Running terraform apply..."
    silent: true